# Powershell script: This script is to put an alerting on a window service. This script is tested on Powershell version 2.0 and should be working on above as well.
#
# Following parameters in the script needs to be configured as required
# A. MAILSERVER:	This needs to be replace with the smtp mail server details (like NAME/IP etc.) to deliver mail.
# B. SERVICENAME:	This needs to be replace with the actual service name which needs to be monitored.
# C. From, To, Cc:	Here correct email needs to be provided in the SEND-MAILMESSAGE function
#


Try
{
    $serverName = [system.environment]::MachineName 
    $ServiceName = SERVICENAME
    $objService = Get-Service -Name $ServiceName 	
    if($objService.Status -ne "Running")
    {
        Write-Host("Job is not running, some issue occured.")
        #Notify recipients for taking corrective action.
        Send-MailMessage -from "abc@abc.com" -to "def@def.com" -cc "abc@abc.com"  -Subject "Service found stopped on - $serverName"  -Body "Hi Team <br/><br/> Service is found in stopped state. <br/><br/>Notification will be shared once the service gets started again. <br/><br/> Regards,<br/><br/><br/> ** Please do not reply to this email as it is autogenerated email.**" -BodyAsHtml -smtpServer MAILSERVER

        #Start the service
        Start-Service $ServiceName
        write-host $objService.status
        write-host 'Service starting'
        
        # Wait for 60 seconds
        Start-Sleep -seconds 60
		
	write-host $objService.status
		
        # refresh property values to the current one
        $objService.Refresh()
		
	write-host 'Refresh done'
	write-host $objService.status

        if ($objService.status -eq 'Running')
        {
            Write-Host 'Service is now Running'
            Send-MailMessage -from "abc@abc.com" -to "def@def.com" -cc "abc@abc.com" -Subject "Service re-started on - $serverName"  -Body "Hi Team <br/><br/> Please be informed that service is up and running now. <br/><br/>There is no further action required. <br/><br/> Regards,<br/><br/><br/> ** Please do not reply to this email as it is autogenerated email.**" -BodyAsHtml -smtpServer MAILSERVER
        }
        else
        {
             Write-Host 'Service did not started after refresh'
             Send-MailMessage -from "abc@abc.com" -to "def@def.com" -cc "abc@abc.com" -Subject "Service restart failed - $serverName"  -Body "Hi Team <br/><br/>Service did not get started even after retry attempt. <br/><br/>Request you to raise a ticket for further investigation on same.<br/><br/> Regards,<br/><br/><br/> ** Please do not reply to this email as it is autogenerated email.**" -BodyAsHtml -smtpServer MAILSERVER
        }

    }
    else
    {
        Write-Host("Job is running fine.")
    } 
}
Catch
{
    #Notify if there is any error occurs
    Send-MailMessage -from "abc@abc.com" -to "def@def.com" -cc "abc@abc.com" -Subject "Fetching Service Status - failed!" -Body "Hi Team <br/><br/> Please be informed that there is some issue reported while fetching status of a service. <br/><br/>Request you to raise a ticket for further investigation on same.<br/><br/> Regards,<br/><br/><br/> ** Please do not reply to this email as it is autogenerated email.**" -BodyAsHtml -SmtpServer MAILSERVER
}



